### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by muralikodali** [pcharest2000/winswitch#1]
font path given in main.h is different for my OS (Arch LInux)

I have changed path suitable to my system (i.e /usr/share/fonts/ubuntu/Ubuntu.B.ttf)

otherwise it gives following error : 

$ ./winswitch
Error 1 opening /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf.
fish: “./winswitch” terminated by signal SIGSEGV (Address boundary error)

**Comment by pcharest2000** [comment]
Confirmed bug,  if the font does not exist it fallback to default Serif font built into the cairo library.  Tks for the repport
